#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: UXDX Conference 2019

# Short bio or description (displayed in the header)
description: Helping teams build products that customers love. Customer Focus (UX) * Technical Excellence (DX) = Product Gold.

#
# Flags below are optional
#


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-78423296-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://uxdxconf.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: "/uxdxconf"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  load_paths:
    - _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules

include: ["_pages"]

# collections:
#   speakers:
#     output: true
#     scope: 
#       path: "speakers/"
#       type

prose:
  rooturl: '_posts'
  siteurl: 'https://uxdxconf.com/'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
          value: "blog"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "Rory Madden"
    _posts/static:
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "blog/:title"